import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("MCP keeps the approval boundary and response limits explicit", async () => {
  const source = await readFile(new URL("../src/index.ts", import.meta.url), "utf8");
  assert.match(source, /legacy:\s*["']stateless["']/);
  assert.match(source, /corsOptions:\s*false/);
  assert.match(source, /text\.length > 1_000_000/);
  assert.match(source, /raw\.length <= 24_000/);
  assert.match(source, /redirect:\s*["']manual["']/);
  assert.doesNotMatch(source, /redirect:\s*["']error["']/);
  assert.match(source, /oauthCompletionResponse/);
  assert.match(source, /http-equiv="refresh"/);
  assert.doesNotMatch(source, /approvals\/[^"`]*\/(approve|deny)/);
  assert.match(source, /server\.registerTool\("chusky_tool_run"/);
  assert.match(source, /server\.registerTool\("chusky_tool_schema_get"/);
  assert.match(source, /server\.registerTool\("chusky_native_tool_run"/);
  assert.match(source, /title:\s*["']Chusky["']/);
  assert.match(source, /const MCP_WEBSITE_URL = ["']https:\/\/chusky-web\.vercel\.app["']/);
  assert.match(source, /websiteUrl:\s*MCP_WEBSITE_URL/);
  assert.match(source, /icons:\s*\[\{\s*src:\s*MCP_ICON_URL,\s*mimeType:\s*["']image\/png["']/);
  assert.match(source, /CHUCK_TOOL_PREFLIGHT.*CHUCK_INTEGRATION_HEALTH.*CHUCK_ARTIFACT_QA.*CHUCK_FILE_BRIDGE.*CHUCK_MEDIA_BRIDGE.*CHUCK_TOOL_RECOVERY/s);
  assert.match(source, /attachments:\s*z\.array\(z\.string\(\)\.min\(1\)\.max\(160\)\)\.max\(5\)/);
  assert.match(source, /body: jsonBody\(\{ input, agentId, metadata, budget, tools, attachments, wait: false \}\)/);
  assert.match(source, /body: jsonBody\(\{ input, attachments, wait: false, budget: \{ maxToolCalls: 1 \}/);
  assert.match(source, /"chusky_run_start"[^\]]*"chusky_tool_run"/s);
  assert.match(source, /tools:\s*\{\s*allow:\s*\[tool\]/);
  assert.match(source, /budget:\s*\{\s*maxToolCalls:\s*1\s*\}/);
  assert.match(source, /If the tool requires human approval, pause/);
  assert.match(source, /NATIVE_TOOL_NAME = \/\^CHUCK_\[A-Z0-9_\]\+\$\//);
  assert.match(source, /\/v1\/tools\/\$\{encodeURIComponent\(toolName\)\}/);
  assert.match(source, /descriptor\.source !== "native"/);
  assert.match(source, /tools: \{ allow: \[toolName\] \}/);
});
